# Generated by Django 4.2 on 2024-10-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
