# Generated by Django 4.2 on 2024-10-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_bookmodel_genre_bookmodel_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
