# Generated by Django 4.2 on 2024-10-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0004_bookmodellog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='users_management.authormodel'),
        ),
        migrations.AlterField(
            model_name='bookmodellog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='book_logs', to='users_management.authormodel'),
        ),
        migrations.AlterField(
            model_name='bookmodellog',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='users_management.bookmodel'),
        ),
    ]
